//
// Generated file, do not edit! Created by nedtool 5.6 from messages/labelMessage.msg.
//

#ifndef __LABELMESSAGE_M_H
#define __LABELMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/labelMessage.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet LabelMessage
 * {
 *     string label;
 *     int label_size;
 * }
 * </pre>
 */
class LabelMessage : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string label;
    int label_size;

  private:
    void copy(const LabelMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LabelMessage&);

  public:
    LabelMessage(const char *name=nullptr, short kind=0);
    LabelMessage(const LabelMessage& other);
    virtual ~LabelMessage();
    LabelMessage& operator=(const LabelMessage& other);
    virtual LabelMessage *dup() const override {return new LabelMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getLabel() const;
    virtual void setLabel(const char * label);
    virtual int getLabel_size() const;
    virtual void setLabel_size(int label_size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LabelMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LabelMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __LABELMESSAGE_M_H

